name: flutter_responsive_debugger_example
description: Example app demonstrating flutter_responsive_debugger package.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_responsive_debugger: ^1.0.0
    # path: ../ # Uncomment for local development

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
