name: flutter_responsive_debugger
description: A dev-only overlay to debug and preview responsive layouts in Flutter apps without switching emulators.
version: 1.0.4

# Changelog
# 1.0.4
# - Added demo GIF to README for better visualization

# 1.0.3
# - Fixed default device selection in dropdown to properly handle current screen size
# - Resolved duplicate value issue in device dropdown
# - Improved cross-platform compatibility
# - Added proper null safety for device selection
homepage: https://github.com/wajahatiqbal22/flutter_responsive_debugger
repository: https://github.com/wajahatiqbal22/flutter_responsive_debugger

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
